services:

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:5173"
    command: npm run dev -- --host
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pokemon-server
    ports:
      - "8887:8887"
    depends_on:
      - frontend